worker_processes 1;

events {
    worker_connections 1024;
}

http {
    sendfile on;

    resolver 127.0.0.11 valid=2s;

    # группа серверов для сервиса заказов
    upstream orders_backend {
        server orders_service:8002;
    }

    # группа серверов для сервиса продуктов пока не ворк потому что в докере нету
    # upstream products_backend {
    #     server products_service:8000;
    # }

    server {
        listen 80;
        server_name localhost;

        # все запросы начинающиеся с /api/orders, отправляем в orders_service
        location /api/orders {
            proxy_pass http://orders_backend/api/orders;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # все запросы начинающиеся с /api/products, отправляем в products_service
        # location /api/products/ {
        #     rewrite ^/api/products/(.*) /products/$1 break;
        #     proxy_pass http://products_backend;
        #     proxy_set_header Host $host;
        #     proxy_set_header X-Real-IP $remote_addr;
        #     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        # }
    }
}